FROM python:3.9-alpine3.13

RUN adduser -D redis-client

USER redis-client

WORKDIR /app

RUN pip install --user --no-cache-dir flask redis

COPY redis-client.py ./

CMD [ "python", "redis-client.py" ]