apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: suraj08/first-app:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
          name: first-app-port
          # targetPort: 80
        env:
          - name: REDIS_PORT
            value: '8080'


---


kind: Service
apiVersion: v1
metadata:
  name: first-app
spec:
  selector:
    app: first-app
  type: NodePort
  ports:
  - name:  http
    port:  8080
    nodePort: 30000
    targetPort: first-app-port