name: build and push to dockerhub

on:
  push:
    branches:
      - pre-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the first-app image
        working-directory: first-app
        run: |
          docker buildx build --push \
            --tag suraj08/first-app:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
      - name: build the redis-client image
        working-directory: redis-client
        run: |
          docker buildx build --push \
            --tag suraj08/redis-client:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .